dist: xenial
language: cpp
os:
  - linux
arch:
  - arm64
  - ppc64le
compiler:
  - clang
  - gcc
cache:
  - ccache

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgflags-dev
      - libbz2-dev
      - liblz4-dev
      - libsnappy-dev
      - liblzma-dev  # xv
      - libzstd-dev
      - zlib1g-dev

matrix:
  - os : linux
    arch: arm64
    env: JOB_NAME=cmake-mingw
  - os : linux
    arch: arm64
    env: JOB_NAME=make-gcc4.8
