dist: xenial
language: cpp
os:
  - linux
arch:
  - arm64
  - ppc64le
compiler:
  - clang
  - gcc
cache:
  - ccache

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgflags-dev
      - libbz2-dev
      - liblz4-dev
      - libsnappy-dev
      - liblzma-dev  # xv
      - libzstd-dev
      - zlib1g-dev

env:
  - TEST_GROUP=platform_dependent # 16-18 minutes
  - TEST_GROUP=1 # 33-35 minutes
  - TEST_GROUP=2 # 18-20 minutes
  - TEST_GROUP=3 # 20-22 minutes
  - TEST_GROUP=4 # 12-14 minutes
  # Run java tests
  - JOB_NAME=java_test # 4-11 minutes
  - JOB_NAME=lite_build # 3-4 minutes
  - JOB_NAME=examples # 5-7 minutes
  - JOB_NAME=cmake # 3-5 minutes
  - JOB_NAME=cmake-gcc8 # 3-5 minutes
  - JOB_NAME=cmake-gcc9 # 3-5 minutes
  - JOB_NAME=cmake-gcc9-c++20 # 3-5 minutes
  - JOB_NAME=cmake-mingw # 3 minutes
  - JOB_NAME=make-gcc4.8
  - JOB_NAME=status_checked

matrix:
  - os : linux
    arch: arm64
    env: JOB_NAME=cmake-mingw
  - os : linux
    arch: arm64
    env: JOB_NAME=make-gcc4.8
